# gonelist 配置文件，注意配置字段和信息中间有个空格

# name 表示你的站点的名字，会显示在每个页面的左上角
name: GONEList
# page_title 是在浏览器标签栏的名字
page_title: GONEList

# gonelist 服务设置，不建议修改
server:
  ReadTimeout: 60
  WriteTimeout: 60
  bind_global: true  # 是否绑定到全局（0.0.0.0），如果使用 nginx 转发可以设置为 false
  dist_path: ./dist/ # 前端文件路径，请不要修改
  gzip: true         # 是否开启 gzip 加速, 默认开启
  port: 8000         # 应用监听的端口
  site_url: http://localhost:8000 # 不建议修改，在启动后会自适应调整
  enable_upload: false  # 是否开启上传功能

admin:
  # 是否允许客户端写入文件到onedrive服务端，写入包括创建文件夹，上传文件，删除文件
  enable_write: false
  # 写入权限的secret，前端升级权限时需要，建议更改默认secret
  secret: 123465

  # 大文件分片上传时得分片大小，默认为32MB,数字为1表示320kb
  upload_slice_size: 100


# 本地文件挂载配置，请谨慎挂载，挂载后在管理员权限下将拥有删除文件和上传文件的权限
local:
  # 是否启用本地文件挂载
  enable: false
  # 本地文件挂载的名称，即挂载目录在跟目录显示的名称
  name: local
  # 本地文件挂载的路径，请使用/而不是\\,支持绝对路径和相对路径
  # eg: 绝对路径 D:/Test  /root/test
  # eg: 相对路径 ./test  ../
  path: ./

# webdav配置
web_dav:
  # 是否启用webdav
  enable: false
  # webdav监听地址
  host: 0.0.0.0
  # webdav监听端口
  port: 80
  # webdav登录账号
  account: admin
  # webdav登录密码
  password: admin

# 网盘挂载的类型，当前仅支持 onedrive
list_type: onedrive

# onedrive 设置选项
onedrive:
  # Remote name，可选 onedrive, chinacloud（世纪互联）,可选local,选中local时仅支持挂载本地目录
  remote: onedrive

  # onedrive 的刷新模式，all，fresh 两种模式
  # all 模式下每次都自动刷新所有文件，默认配置
  # fresh 模式下，对文件数量极多的用户比较友好，只刷新 level 层的文件，其他文件夹在访问后延迟刷新
  model: all

  # model 为 fresh 才生效，onedrive 的获取层级，默认获取两层
  level: 2

  # 自动刷新时间，单位分钟
  refresh_time: 60

  # 提供 onedrive 的应用配置，建议自己创建应用
  client_id: 16e320f7-e427-4612-88da-f3d03e944d40
  client_secret: lURpL3U@bBlmJ0:_dnU.LeLOGNGdVT30
  # 提供 chinacloud 的应用配置，建议自己创建应用
  #client_id: 2b54b127-b403-42a3-8b55-d25f3119aa13
  #client_secret: a0CGqBT3f_8U5gztxKjxR-LNW-ZnTe.m

  # 子文件夹设置，比如你只想挂载你盘根目录下的 public 文件夹，就使用 /public
  folder_sub: /

  # 不建议修改，需要和应用中心设置的 redirect_url 一致
  redirect_url: http://localhost:8000/auth

  # 随意设置一个你喜欢的字符串，在 onedrive 认证时会使用
  state: 23333

  # 默认在当前文件夹下，不建议修改
  # token 实现了下次启动时不需要重新登陆验证的功能
  token_path:

  # 可以配置 CDN 加速重定向，url 前缀
  download_redirect_prefix:

  # 这是一个数组，可以对不同文件夹设置密码
  # 但还是推荐在需要设置密码的文件夹下创建 .password 文件
  # 在该文件中填写密码即可，文件格式最好是 UTF-8
  pass_list:
    - pass:
      path:
  #  - pass:
  #    path:
  

